name: 'Redis Cluster with Master-Slave'
description: 'Setup Redis cluster with 3 master and 3 slave in a single container'
author: 'Mohammed Belcaid'
branding:
  icon: 'database'
  color: 'red'
inputs:
  master1-port:
    description: 'Port number for master1'
    required: false
    default: 5000
  master2-port:
    description: 'Port number for master2'
    required: false
    default: 5001
  master3-port:
    description: 'Port number for master3'
    required: false
    default: 5002
  slave1-port:
    description: 'Port number for slave1'
    required: false
    default: 5003
  slave2-port:
    description: 'Port number for slave2'
    required: false
    default: 5004
  slave3-port:
    description: 'Port number for slave3'
    required: false
    default: 5005
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.master1-port }}
    - ${{ inputs.master2-port }}
    - ${{ inputs.master3-port }}
    - ${{ inputs.slave1-port }}
    - ${{ inputs.slave2-port }}
    - ${{ inputs.slave3-port }}
